### ISSUE TITLE
Program doesn't stop after cleaning up

### ISSUE THREAD

**Issue by LotekHeavy** [Impulse87/ATLAS-RawTravelDataCleaner#1]
I could start the program, but it seems it stays in a loop. after a while it stops doing anything, but its not quit, so I forced with CTRL+C to end. Or should the programm stay in the background while the atlas server is running?

**Comment by Impulse87** [comment]
You can leave it running in the background. It only cycles every 10 minutes through your redis db. So that it doesn't waste server resources.

**Comment by LotekHeavy** [comment]
OK, thanks!
