### ISSUE TITLE
Not sure this is working?

### ISSUE THREAD

**Issue by smooreace** [Impulse87/ATLAS-RawTravelDataCleaner#2]
I was under the impression that this helped to take care of old sunk ship data on the territory map. It seems to be running, but its not removing anything thats noticeable. Have I misunderstood something? I do get this...
https://gyazo.com/ebaa47a630ab86c9dcb1f428371d709b

**Comment by Impulse87** [comment]
Nope it does only set a timestamp for data in your redis DB. Those ghost ships are written in the savegame of corresponding grid server... which means i didn't find a way to clear that problem yet.

**Comment by smooreace** [comment]
Gotcha. Thank you.
